[versions]
shadow = "8.3.3"
blossom = "2.1.0"
moddevgradle = "1.0.21"
forgegradle = "[6.0,6.2)"
loom = "1.10-SNAPSHOT"
licenser = "0.6.1"
kotlin = "2.1.10"
ideagradle = "1.1.10"

adventure_main = "4.19.0"
adventure_platform = "4.3.4"
indra = "3.1.3"
examination = "1.3.0"
fastutil = "8.5.15"
xseries = "13.0.0"
yamlengine = "2.9"
asm = "9.7"
gson = "2.11.0"
caffeine = "3.1.5"
guava = "31.1-jre"
hikari = "6.0.0"
mongodb = "5.2.1"

[plugins]
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
moddevgradle = { id = "net.neoforged.moddev", version.ref = "moddevgradle" }
forgegradle = { id = "net.minecraftforge.gradle", version.ref = "forgegradle" }
loom = { id = "fabric-loom", version.ref = "loom" }
licenser = { id = "org.cadixdev.licenser", version.ref = "licenser" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ideagradle = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "ideagradle" }


[libraries]

# Engines
yamlengine = { group = "org.snakeyaml", name = "snakeyaml-engine", version.ref = "yamlengine" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

kyori_advntr_key = { group = "net.kyori", name = "adventure-key", version.ref = "adventure_main" }
kyori_advntr_api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure_main" }
kyori_advntr_nbt = { group = "net.kyori", name = "adventure-nbt", version.ref = "adventure_main" }
kyori_advntr_text_bungee = { group = "net.kyori", name = "adventure-text-serializer-bungeecord", version.ref = "adventure_platform" }
kyori_advntr_text_gson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure_main" }
kyori_advntr_text_json = { group = "net.kyori", name = "adventure-text-serializer-json", version.ref = "adventure_main" }
kyori_advntr_text_plain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure_main" }
kyori_advntr_text_legacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure_main" }
kyori_advntr_text_minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure_main" }
kyori_advntr_platform_bukkit = { group = "nei.kyori", name = "adventure-platform-bukkit", version.ref = "adventure_platform" }
kyori_advntr_platform_bungee = { group = "net.kyori", name = "adventure-platform-bungeecord", version.ref = "adventure_platform" }
kyori_advntr_event = { group = "net.kyori", name = "event-api", version = "3.0.0" }

kyori_examination_api = { group = "net.kyori", name = "examination-api", version.ref = "examination" }
kyori_examination_string = { group = "net.kyori", name = "examination-string", version.ref = "examination" }

kyori_mammoth = { group = "net.kyori", name = "mammoth", version = "1.4.0" }
kyori_indra_common = { group = "net.kyori", name = "indra-common", version.ref = "indra" }
kyori_lunar = { group = "net.kyori", name = "lunar", version = "1.0.6" }

xseries = { group = "com.github.cryptomorin", name = "XSeries", version.ref = "xseries" }

asm_asm = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
asm_commons = { group = "org.ow2.asm", name = "asm-commons", version.ref = "asm" }

kryo = { group = "com.esotericsoftware", name = "kryo", version = "5.6.2" }

apache_commons_io = "commons-io:commons-io:2.18.0"
apache_commons_lang = "org.apache.commons:commons-lang3:3.13.0"
apache_commons_math = "org.apache.commons:commons-math3:3.6.1"
apache_commons_text = "org.apache.commons:commons-text:1.13.0"
apache_commons_compress = "org.apache.commons:commons-compress:1.27.1"
apache_commons_config = "org.apache.commons:commons-configuration2:2.11.0"
apache_commons_collections = "org.apache.commons:commons-collections4:4.5.0-M3"
apache_commons_exec = "org.apache.commons:commons-exec:1.4.0"


fastutil = { group = "it.unimi.dsi", name = "fastutil", version.ref = "fastutil" }

caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }

hikari = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikari" }

mongodb_core = { group = "org.mongodb", name = "mongodb-driver-core", version.ref = "mongodb" }
mongodb_bson = { group = "org.mongodb", name = "bson", version.ref = "mongodb" }
mongodb_sync = { group = "org.mongodb", name = "mongodb-driver-sync", version.ref = "mongodb" }

h2 = { group = "com.h2database", name = "h2", version = "2.3.232" }

postgresql = { group = "org.postgresql", name = "postgresql", version = "42.7.5" }

# ClassPath Libs
annotations_jetbrains = { group = "org.jetbrains", name = "annotations", version = "26.0.1" }
annotations_checker = { group = "org.checkerframework", name = "checker-qual", version = "3.46.0" }
