main: org.kingdoms.outposts.OutpostAddon
name: "${project.name}"
description: "${project.description}"
author: Crypto Morin
version: "${project.version}"
api-version: "1.13"
depend: [ Kingdoms, Kingdoms-Addon-EngineHub ]
