name: "${project.name}"
version: "${project.version}"
description: "${project.description}"
main: top.mckingdom.powerfulterritory.PowerfulTerritoryAddon
api-version: "1.20"
depend: [ Kingdoms, Kingdoms-Addon-Auspice ]

