package net.aurika.dyanasis;

public final class DyanasisKeywords {
    public static final String RETURN = "return";
    public static final String THIS = "this";
    public static final String SUPER = "super";
    public static final String IMPLEMENTS = "implements";
    public static final String ABSTRACT = "abstract";
    public static final String FINAL = "final";
    public static final String STATIC = "static";
    public static final String SYNCHRONIZED = "synchronized";
    public static final String VOLATILE = "volatile";
    public static final String TRANSIENT = "transient";
    public static final String NATIVE = "native";
    public static final String STRICTFP = "strictfp";
    public static final String IF = "if";
    public static final String ELSE = "else";
    public static final String WHILE = "while";
    public static final String FOR = "for";
    public static final String DO = "do";
    public static final String SWITCH = "switch";
    public static final String DEFAULT = "default";
    public static final String FINALLY = "finally";
    public static final String THROW = "throw";
    public static final String CATCH = "catch";
    public static final String ACCEPT = "accept";
    public static final String CONSTRUCT = "construct";
    public static final String ENUM = "enum";
    public static final String ANY = "any";
    public static final String NULL = "null";
    public static final String VOID = "void";
    public static final String BOOLEAN = "boolean";
    public static final String CHAR = "char";
    public static final String BYTE = "byte";
    public static final String SHORT = "short";
    public static final String INT = "int";
    public static final String LONG = "long";
    public static final String FLOAT = "float";
    public static final String DOUBLE = "double";
    public static final String CLASS = "class";
    public static final String INTERFACE = "interface";
    public static final String UNDERLINE = "_";
}