name: "${project.name}"
version: "${project.version}"
description: "${project.description}"
main: net.aurika.kingdoms.territories.TerritoriesAddon
api-version: "1.20"
depend: [ Kingdoms, Kingdoms-Addon-Auspice ]
