main: org.kingdoms.enginehub.EngineHubAddon
name: "${project.name}"
description: "${project.description}"
author: Crypto Morin
version: "${project.version}"
api-version: "1.13"
depend: [ Kingdoms, WorldEdit ]
softdepend: [ WorldGuard ]
